name: dplpy3
channels:
  - conda-forge
  - defaults
dependencies:
  - bs4
  - pandas
  - matplotlib
  - wget
  - statsmodels
  - numpy
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.2.1=hecd8cb5_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1m=hca72f7f_0
  - pip=21.2.4=py310hecd8cb5_0
  - python=3.10.0=hdfd78df_5
  - readline=8.1.2=hca72f7f_1
  - setuptools=58.0.4=py310hecd8cb5_0
  - sqlite=3.37.2=h707629a_0
  - tk=8.6.11=h7bc2e8c_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h4dc903c_4
  - scipy
